# Generated by Django 2.0.6 on 2018-07-13 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField(default='C++')),
                ('code', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField(default='等待评测')),
                ('memory', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('info', models.TextField(null=True)),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MyUser')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
            ],
            options={
                'ordering': ('-create_time',),
            },
        ),
    ]
