# Generated by Django 2.0.6 on 2018-07-13 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submission', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField(default='Waiting')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MyUser')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Submission')),
            ],
            options={
                'ordering': ('-create_time',),
            },
        ),
    ]
